name: translations-check
run-name: Checking if PR made by ${{ github.actor }} might need translations
on:
  pull_request:
    types: [opened]
jobs:
  check:
    uses: adpaste/textunited-actions/workflows/check-translations.yml@main